name: typecheck
on: [pull_request]
jobs:
  check:
    name: typecheck
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: install dependencies
        run: yarn install --frozen-lockfile

      - name: type check
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx tsc -p tsconfig.json --pretty false --noEmit | reviewdog -f=tsc -reporter=github-pr-review -fail-on-error=true
